### ISSUE TITLE
Esercizio prolog "re" del 2022/07/05

### ISSUE THREAD

**Issue by jaco-99** [DennisTurco/Intelligenza-Artificiale#1]
Se vi può interessare io l'ho fatto in questo modo:

``` Prolog
re(n, [N]) :- integer(N).

re(s(P),L) :-
    re(P,L).

re(o(P1,P2),L) :-
    re(P1,L);
    re(P2,L).

re(c(P1,P2),L) :-
    append(L1, L2, L),
    re(P1,L1),
    re(P2,L2).

% re(o(c(n, n), c(n, c(n, n))), [1,2,3]).
% re(s(o(c(n, n), c(n, c(n, c(n, n))))), [1,2,3,4,5,6,7]).
```

**Comment by Davoleo** [comment]
Interessante l'approccio per `c(P1,P2)` è sicuramente più compatto di quello che è venuto in mente a me e funziona correttamente.

Per il resto ho testato su SWISH, ma l'implementazione di `s(P)` per com'è fatta non ha effetto, dovrebbe funzionare circa come la stella di Kleene nelle espressioni regolari e rendere vere occorrenze multiple o nulle del pattern P (sempre se ho capito correttamente), ma per come è scritto non fa altro che ridirezionare la richiesta unwrappando il pattern dentro `s`, ho una mezza idea su come implementarlo ma c'è bisogno di un'altro parametro, e volevo evitarlo, ci penserò su in questi giorni

**Comment by jaco-99** [comment]
Si, hai ragione. Non credo di aver capito bene quale dovrebbe essere il comportamento di `s`. Anche dall'esempio che ha mostrato il professore nel compito, non mi è molto chiaro.

**Comment by Davoleo** [comment]
Abbiamo implementato `re(s(P))`, ho scritto anche dei commenti nel file per spiegare il funzionamento.
Commit Ref: https://github.com/DennisTurco/Intelligenza-Artificiale/commit/b71290af76da3cf968f233d39f9ce060ddfc72a6

**Comment by Davoleo** [comment]
Non ho aggiunto la tua versione dei predicati con 2 parametri perché non ho trovato il modo di fare `re(s(P), L)`  correttamente (se tu hai un idea scrivi pure e aggiungerò anche la tua versione alternativa), perché non da informazioni sulla lunghezza del pattern P che viene valutato nella sottochiamata e quindi non è possibile rimuovere N elementi dalla lista L e conseguentemente non è possibile arrivare a un caso base per `s`.
